Add .env.example file and update README.md
collabo-community/collabocate pull request #1
Opened 2024-06-17 18:22 UTC by KBandipo

Add .env.example and update README.md

2024-06-17 18:38 UTC, KBandipo commented
PR ready for review @collabo-community/review-web-app @Ifycode

2024-06-19 11:11 UTC, Ifycode requested changes

2024-06-19 11:11 UTC, Ifycode commented on .env.example
> +# GitHub API Token
Question is this description of the token "GitHub API token" correct?
What type of github token is the user to use here: 
- User access token?
- Personal access token?
- Github API token?

You want to state it exactly as it is to not leave a user/contributor confused.

Advising that you go to the place where you generated the token from and update this description accordingly @KBandipo

2024-06-19 11:13 UTC, Ifycode commented
PR title also just says "Update", so what exactly are you updating? @KBandipo

2024-06-19 13:07 UTC, KBandipo commented on .env.example
> +GITHUB_TOKEN=your_github_token_here
Done

2024-06-19 13:07 UTC, KBandipo commented on .env.example
> +# GitHub API Token
Done

2024-06-19 13:09 UTC, KBandipo commented
Pull Request ready for review @collabo-community/review-web-app @Ifycode

2024-06-19 14:32 UTC, Ifycode commented on .env.example
> +GITHUB_TOKEN=your_github_token_here
You can make this part better desciptive as I have explained in the "Also note" part @KBandipo and change it in everywhere else it appears in the code.

2024-06-19 14:33 UTC, Ifycode commented
See comment here: https://github.com/collabo-community/collabocate/pull/1#discussion_r1646313107
@KBandipo

2024-06-19 18:14 UTC, KBandipo commented on .env.example
> +GITHUB_TOKEN=your_github_token_here
Okay, I'll do that now

2024-06-19 18:42 UTC, KBandipo commented
I have made the requested changes, please review the updates @collabo-community/review-web-app @Ifycode

2024-06-19 21:08 UTC, Ifycode approved these changes

2024-06-19 21:09 UTC, merged