fix: separate the port for server.js from the one for your basic frontend
collabo-community/collabocate pull request #11
Opened 2024-07-06 05:21 UTC by tylerjusfly

**This pull request makes the following changes :**
https://discord.com/channels/1148391778492354741/1253584233155395657/1253596919578759289

### HOW TO TEST

- Run `npm run start:client` in the root folder to start the client server.
- Run `npm run start` in the root folder to start the server
- Visit PORT `8080` to view the frontend

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on.
- [x] I have linked the issue I worked on to this pull request submitted by me.
- [x] Everything works as before.

2024-07-06 09:10 UTC, Ifycode requested changes

2024-07-06 09:10 UTC, Ifycode commented on server.js
> +app.use(cors());
App breaks @tylerjusfly 
Check that you have added the package to the project.

2024-07-06 09:24 UTC, tylerjusfly commented on server.js
> +app.use(cors());
done.

2024-07-06 15:30 UTC, merged

2024-07-12 02:09 UTC, Ifycode commented
@all-contributors add @tylerjusfly for code