Fix: Top portion of issue body content should not display
collabo-community/collabocate pull request #28
Opened 2024-12-03 23:15 UTC by KBandipo

#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#41

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

- [x] Issue body displays the appropriate template content, and unintended content at the top is not shown.
- [x] I certify that I ran my checklist

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

2024-12-03 23:17 UTC, KBandipo commented
Ready for review

2024-12-04 16:07 UTC, Ifycode requested changes

2024-12-09 17:20 UTC, KBandipo commented on @dev-client/views/@plugin_githubsync/githubsync.js
> +    }
Copy

2024-12-10 08:35 UTC, KBandipo commented on @dev-client/views/@plugin_githubsync/githubsync.js
> +    }
@Ifycode 
Ready for review

2024-12-10 16:21 UTC, Ifycode approved these changes

2024-12-10 16:21 UTC, merged