Move GitHub API URL to .env
collabo-community/collabocate pull request #4
Opened 2024-06-24 08:53 UTC by KBandipo

This pull request refactors the code to use an environment variable for the GitHub API base URL. These were the changes made

- Added GITHUB_API_URL to the .env.
- Updated server.js to use the base URL from the environment variable for API requests and merge with the endpoints (/issues and /pulls).
- Updated the .env.example file to reflect the new GITHUB_API_URL variable.

2024-06-24 08:56 UTC, KBandipo commented
Hello @collabo-community/review-web-app, my PR is ready for review. Thank you

2024-06-24 20:30 UTC, Ifycode requested changes

2024-06-24 20:30 UTC, Ifycode commented on server.js
> +const GITHUB_PR_API_URL = `${GITHUB_API_URL}/pulls`;
Nice try @KBandipo 
There's no need to store them again in variables in lines 14-16.

You can remove lines 14 - 16 from the code, the apply the .env variable directly like so:

````
const response = await fetch(`${process.env.GITHUB_API_URL}/issues`
````

Same for /pulls too.

2024-06-25 10:42 UTC, KBandipo commented on server.js
> +const GITHUB_PR_API_URL = `${GITHUB_API_URL}/pulls`;
Hummmh, keep it DRY (Don't Repeat Yourself),  thanks boss. That's why it's good to work with senior dev

2024-06-25 11:04 UTC, KBandipo commented
Hello @collabo-community/review-web-app, my PR is ready; I have refactored the code

2024-06-25 11:41 UTC, Ifycode approved these changes

2024-06-25 11:43 UTC, merged