Migrated server code to TypeScript
collabo-community/collabocate pull request #5
Opened 2024-06-25 15:31 UTC by Danbaba1

* **Converted server-side JavaScript code to TypeScript for improved type safety and maintainability.**
* **Updated server to use TypeScript for enhanced static typing and potential code improvements.**

2024-06-25 15:40 UTC, Danbaba1 commented
**Please review my pull request** @collabo-community/review-backend-api

2024-06-26 02:55 UTC, Ifycode requested changes

2024-06-26 02:55 UTC, Ifycode commented on server/src/server.ts
> +const PORT = parseInt(process.env.PORT || '3000', 10); // Ensure PORT is a number
Nice work so far @Danbaba1 

But there is no need to check PORT here. Just do it as you see it is done in our templates.

2024-06-26 02:55 UTC, Ifycode commented on server/tsconfig.json
> +  "compilerOptions": {
For tsconfig, is this the exact configuration in our template?
If not, you want to remove what's here and copy the contents of our template's tsconfig here instead @Danbaba1

2024-06-26 02:55 UTC, Ifycode commented on server/package.json
>    "dependencies": {
I see dependencies coming first and the order of things generally rearranged in your package.json here. We want the order of things in the package.json to be exactly the same as that of our templates. Make the changes accordingly @Danbaba1

2024-06-26 02:55 UTC, Ifycode commented on server/package.json
> +    "typescript": "^5.5.2"
For both dependencies and devDependecies in your package.json. As long as you can find it in our own template, use the same exact versions you find there in here @Danbaba1

2024-06-26 02:55 UTC, Ifycode commented on server/package.json
> +    "start": "nodemon --exec ts-node src/server.ts"
@Danbaba1 Eslint: 
- `lint` and `lint-watch` scripts are missing in your package.json (and in your dependencies)
- Also all files that configures or that makes eslint work are not present

> Ensure that eslint alerts coding issues in this server also, just like it does in our template.

2024-06-26 02:55 UTC, Ifycode commented on server/src/app.ts
> +
Morgan is missing here and as a package. We want Morgan to give status report for our API in the terminal. See our template for how Morgan works and is implemented @Danbaba1

2024-06-26 02:55 UTC, Ifycode commented on server/src/app.ts
> +
Wondering why you left out the CORS part here and in the package.json @Danbaba1 
Implement it as done in our template.

2024-06-26 06:38 UTC, Danbaba1 commented on server/src/server.ts
> +const PORT = parseInt(process.env.PORT || '3000', 10); // Ensure PORT is a number
I will make the necessary changes ma.

2024-06-26 06:39 UTC, Danbaba1 commented on server/tsconfig.json
> +  "compilerOptions": {
I will make the necessary changes ma.

2024-06-26 06:39 UTC, Danbaba1 commented on server/package.json
>    "dependencies": {
I will make the necessary changes ma.

2024-06-26 06:39 UTC, Danbaba1 commented on server/package.json
> +    "typescript": "^5.5.2"
I will make the necessary changes ma.

2024-06-26 06:39 UTC, Danbaba1 commented on server/package.json
> +    "start": "nodemon --exec ts-node src/server.ts"
I will make the necessary changes ma.

2024-06-26 06:39 UTC, Danbaba1 commented on server/src/app.ts
> +
I will make the necessary changes ma.

2024-06-26 06:39 UTC, Danbaba1 commented on server/src/app.ts
> +
I will make the necessary changes ma.

2024-06-28 19:54 UTC, Danbaba1 commented
Made necessary changes as requested. Please review PR. @collabo-community/review-backend-api

2024-07-01 15:26 UTC, Danbaba1 commented
https://discord.com/channels/1148391778492354741/1253584233155395657/1253633682821091438

2024-07-01 22:10 UTC, Ifycode requested changes
You also left out some files like the `editorconfig`, `.env.example` etc.
@Danbaba1 please thoroughly check that you have added all the necessary files before you request for review again. You should be making this server as close as possible to our template, not waiting for me to tell you to add them.

For the `.env.example` file just modify it slightly (logically) based on the environment variables we are using in this case.

2024-07-02 10:37 UTC, Danbaba1 commented on package-lock.json
> -      "devDependencies": {}
Okay ma. Noted

2024-07-05 14:03 UTC, closed without merging

2024-07-05 14:04 UTC, Danbaba1 commented
Don't need it again.