Fetch repositories
collabo-community/collabocate pull request #8
Opened 2024-06-29 19:13 UTC by KBandipo

Add functionality to fetch the list of all public repositories on GitHub, alongside their repository links using Get request and display them on the UI upon page load

2024-06-29 19:15 UTC, KBandipo commented
Hello @collabo-community/review-web-app , my PR is ready for review. Thank you

2024-07-01 04:18 UTC, Ifycode requested changes

2024-07-01 04:18 UTC, Ifycode commented on .env.example
> +GITHUB_REPOS_API_URL=https://api.github.com/user/repos
Hmm... Let's see if we can reuse variables inside of the .env file @KBandipo
- See stackoverflow comment: https://stackoverflow.com/a/67615097
- Additional resource just incase: https://stackoverflow.com/a/48794954

2024-07-03 14:17 UTC, KBandipo commented
My pull request is ready for review. I have reused the base url variable inside of the .env file. This is the link to the task issue https://discord.com/channels/1148391778492354741/1253584233155395657/1253594458172297270
Thank you

2024-07-05 18:10 UTC, Ifycode requested changes
Nice Work @KBandipo 
Let's just clean it up a bit. See comments below.

2024-07-05 18:10 UTC, Ifycode commented on .env.example
> +GITHUB_REPOS_API_URL=${BASE_URL}/user/repos
You can just remove this one from here entirely, then you can use it in the code directly like this:

`${process.env.GITHUB_API_BASE_URL}/user/repos`

2024-07-05 21:08 UTC, Ifycode requested changes
@KBandipo always link your issue to your PR. Add your issue link approriately.

2024-07-05 22:42 UTC, Ifycode commented
@KBandipo I have the same question to ask you. the one that I asked Daniel. 
The link to your issue is in the wrong place. How do you expect reviewers/users to find it where you currently added it?

2024-07-06 16:01 UTC, Ifycode requested changes

2024-07-06 16:01 UTC, Ifycode commented on package-lock.json
>        "dependencies": {
package-lock.json should not be showing in your file changes @KBandipo

2024-07-07 19:25 UTC, KBandipo commented on .env.example
> +BASE_URL=https://api.github.com
Okayyyy

2024-07-07 19:25 UTC, KBandipo commented on .env.example
> +GITHUB_API_URL=${BASE_URL}/repos/your-own-github-account-user-name-will-be-here-instead/the-name-of-the-repo-you-want-to-interact-with
Copy boss

2024-07-07 19:35 UTC, KBandipo commented on package-lock.json
>        "dependencies": {
Alright, @Ifycode  please how can I restore it?

2024-07-07 20:26 UTC, KBandipo commented
Howdy boss, I have restored the package-lock.json as you requested @collabo-community/review-collabocate . I'm still working on the other things you corrected too. Thank you

2024-07-08 09:45 UTC, KBandipo commented
Hello @collabo-community/review-collabocate , my pull request is ready for review. These are my changes as you have requested; I replaced `BASE_URL` with `GITHUB_API_BASE_URL` and `GITHUB_API_URL` to `REPO_URL` in `.env.example`;  and Refactored the usage of Github Repositories API URL to `process.env.GITHUB_API_BASE_URL` directly in the server.js

2024-07-08 09:49 UTC, tylerjusfly commented
It says that you have a conflict, can you resolve that @KBandipo ?

2024-07-08 11:46 UTC, KBandipo commented
@tylerjusfly Thank you boss, I may not be able to resolve the conflict myself since I am not the only one working on the old server. @Ifycode is managing the issues together

2024-07-09 02:00 UTC, Ifycode requested changes
@KBandipo you are yet to link your issue to the PR properly, I'm still waiting for this before I can touch/review your PR.

#

> About conflicts, @tylerjusfly I'll be the one to resolve the conflicts (it's caused by the restructuring I'm doing based all our 4 different PRs), so @KBandipo should not worry about the conflicts in this case

2024-07-09 08:32 UTC, KBandipo commented
Thank you @Ifycode , I have linked the issue to the pull request now. Please let me know if there are any additional steps I need to take

2024-07-09 10:01 UTC, Ifycode approved these changes

2024-07-09 12:46 UTC, merged

2024-07-12 02:13 UTC, Ifycode commented
@all-contributors add @KBandipo for code