Revamped the content of the server folder
collabo-community/collabocate pull request #9
Opened 2024-07-04 14:09 UTC by Danbaba1

**This pull request revamps the content of the server folder to take the shape of collabo community API..** https://discord.com/channels/1148391778492354741/1253584233155395657/1253633682821091438

2024-07-04 14:54 UTC, Danbaba1 commented
P.R. is ready for review @collabo-community/review-backend-api

2024-07-05 18:39 UTC, Ifycode requested changes

2024-07-05 18:39 UTC, Ifycode commented on server/package-lock.json
>  {
@Danbaba1 Again, you should not be pushing your package-lock.json file among your file changes.

2024-07-05 18:39 UTC, Ifycode commented on server/src/lib/helpers/index.ts
> +const npmLifeCycleEvent = process.env.npm_lifecycle_event;
We don't need line 24 downwards @Danbaba1

2024-07-05 18:39 UTC, Ifycode commented on server/package.json
> +    "dev:atlas": "nodemon --exec ts-node src/server.ts",
@Danbaba1 I don't understand. What is mongoDB "local" and "atlas" script still doing here?
And Where is the script to start your server?

> This is logical - we are not using anything mongoDB here.

What to do: 
- Change `dev:local` to `dev`
- You can remove the one for atlas

2024-07-05 18:40 UTC, Danbaba1 commented on server/package-lock.json
>  {
Okay ma

2024-07-05 18:40 UTC, Danbaba1 commented on server/src/lib/helpers/index.ts
> +const npmLifeCycleEvent = process.env.npm_lifecycle_event;
Noted ma.

2024-07-05 18:41 UTC, Danbaba1 commented on server/package.json
> +    "dev:atlas": "nodemon --exec ts-node src/server.ts",
Okay ma

2024-07-09 01:55 UTC, Ifycode requested changes
See my comment on discord @Danbaba1 
https://discord.com/channels/1148391778492354741/1253466803791990784/1260050452100415538

2024-07-09 11:13 UTC, samuko-things commented on server/package.json
> +  "description": "Typescript (ES Module import/export syntax and async-await asynchronous code handing method) Backend API boilerplate template generated via Collabo Community's create-collabo-app pr
I think there might be a need to change the name and description also.
Or what do you think @collabo-community/review-collabocate?

2024-07-09 13:54 UTC, tylerjusfly commented on server/package.json
> +  "description": "Typescript (ES Module import/export syntax and async-await asynchronous code handing method) Backend API boilerplate template generated via Collabo Community's create-collabo-app pr
sure.

2024-07-09 15:12 UTC, Danbaba1 commented on server/package.json
> +  "description": "Typescript (ES Module import/export syntax and async-await asynchronous code handing method) Backend API boilerplate template generated via Collabo Community's create-collabo-app pr
Okay sir. What should I change it to?

2024-07-10 22:05 UTC, Ifycode commented on server/package.json
> +  "description": "Typescript (ES Module import/export syntax and async-await asynchronous code handing method) Backend API boilerplate template generated via Collabo Community's create-collabo-app pr
Leave the name changing to me - We are yet to determine what this will look like. Plus, we're still in the process of merging 4 peoples changes. That will change after merging. His task is has to do with the structure of the application.

2024-07-10 22:10 UTC, Ifycode requested changes

2024-07-10 22:10 UTC, Ifycode commented on server/package-lock.json
> -  "name": "-github-rest-api-test",
@Danbaba1 You are supposed to restore the package-lock.json to what was there previously, so that it doesn't show up here. So why delete it?

2024-07-10 23:07 UTC, Ifycode requested changes

2024-07-10 23:07 UTC, Ifycode commented on server/package-lock.json
> -  "packages": {
I can still see changes. See my new comment on discord: https://discord.com/channels/1148391778492354741/1260720142476902512/1260734029972373567

2024-07-11 00:00 UTC, Ifycode approved these changes

2024-07-11 00:14 UTC, merged

2024-07-12 02:11 UTC, Ifycode commented
@all-contributors add @Danbaba1 for code